name: comsys-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - simpy                # mô phỏng event-driven
  - matplotlib
  - fastapi
  - uvicorn
  - pydantic
  - rich
  - typer
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - scikit-optimize
